# Configs
version: 3.1
bin_name: "bin0"
threshold_tof: 240
bin_height: 800.0
## Environments
### EC2
EC2:
  host: "54.154.170.192"
  destination_folder: "/home/ubuntu/vm1-node-service/raw_field_data"
  destination_folder_testing: "/home/ubuntu/vm1-node-service/all_data"
  port: "22"
  user: "ubuntu"
  key: "vf-it-5g.pem"
  key_path: "/home/pi/certs/"

### MEC1
MEC:
  host: "91.81.201.26"
  destination_folder: "/home/ubuntu/vm1-node-service/raw_field_data"
  destination_folder_testing: "/home/ubuntu/new_service/vm1-node-service/all_data"
  port: "22"
  user: "ubuntu"
  key: "vf-it-5g.pem"
  key_path: "/home/pi/certs/"

## MQTT TOPICS
mqtt:
  topic_to_subscribe_to: "response/prediction/trash"
  topic_fake: "response/prediction/fake"
  fill_level_fake: "smartbin/fill_levels/fake"
  fill_level_topic: "smartbin/status/bin0"

## Pics INFO
picture:
  folder: "/home/pi/Pictures/"
  width: 240
  height: 240

## Timers (seconds)
timer:
  photo: 10
  door: 30
  idle: 15

## PIN
gpio:
  tof1: 20
  tof2: 16
  door:
    motor: 17
    magnet: 18
  disk:
    motor: 24
    magnet: 21
  blade:
    motor: 25
    magnet: 27


#  motor:
#    door: 17
#    disk: 24
#    blade: 25
#  magnet:
#    door: 18
#    disk: 21
#    blade: 27
